.travis.yml

Migrate to new Docker based Travis infrastructure. See: http://docs.travis-ci.com/user/migrating-from-legacy/. This makes sense since we do not need root.

CI: migrate to new travis infrastructure

---

ovh/client.py
tests/test_client.py

Default timeout is set to 30 seconds for connection and 180 seconds between reads. It can be overridden by passing 'timeout' argument to the Client constructor.
See official [requests documentation](http://docs.python-requests.org/en/latest/user/advanced/#timeouts) about timeouts.

Add timeout for requests

---

examples/README.md
examples/serviceExpiration/api_get_service_that_expired_soon.md
examples/serviceExpiration/serviceThatWillExpired.py

In replacement of http://www.ovh.com/soapi/en/?method=billingGetReferencesToExpired
(and with all current ovh products)

Add example to get services that will expired

---

README.rst

Here is a new example based on a real-world script I developed for my own needs, with the hope it may be useful for the community. I also took the occasion to remove an outdated Runabove example. At some point, i probably should provide an equivalent for "/cloud".

Improve readme examples

---

README.rst
docs/api/ovh/client.rst
docs/api/ovh/consumer_key.rst
docs/index.rst
ovh/__init__.py
ovh/client.py
ovh/consumer_key.py
tests/test_client.py
tests/test_consumer_key.py

And here is the python version of https://github.com/ovh/go-ovh/pull/3. It follows the same design with 3 simple helpers and HTTP Verbs list "constants".
A simple code excerpt being worth a 1000 lines of text, here it is:
```python
API_READ_ONLY       = ["GET"]
API_READ_WRITE      = ["GET", "POST", "PUT", "DELETE"]
API_READ_WRITE_SAFE = ["GET", "POST", "PUT"]
class ConsumerKeyRequest(object):
def add_rule(self, method, path): pass
def add_rules(self, methods, path): pass
def add_recursives_rules(self, methods, path): pass
```
ping @Rbeuque74 @VincentCasse @gregdel @PouuleT @LukeMarlin

add consumer key helpers

---

setup.cfg
setup.py

Some collegues from Lyon told me that recent (0.4.0) ovh package broke after install, as no vendor was installed along.
I packaged the vendors in the tarball, and made sure to add the pem certificate bundle.

Fix: include the vendorized packages and package data in the install process

---

README.rst
ovh/client.py
ovh/config.py
tests/fixtures/custom_ovh.conf
tests/test_client.py
tests/test_config.py

This patch provide a way to read custom config file that can be provided
on runtime.
E.G.:
client = ovh.Client(config_file="ovh.custom.conf")
This is useful when you have to switch from multiple config file.
At least, this is useful to me :p
Signed-off-by: Arnaud Morin <arnaud.morin@corp.ovh.com>

Read custom file on runtime

---

ovh/client.py
tests/test_client.py

OVH API expects Boolean values in the querystring to be sent as lower case 'true' or 'false' string. Such cases are typically represented as checkboxes in https://api.ovh.com/console. This PR adds the fix and the related regression test.
@ncrocfer Can you confirm this fixes your issue before I can merge?

fix: api expects lower case boolean value in querystring. Closes #32

---

.gitignore
ovh/client.py
tests/test_client.py

Previous fix introduced a regression. It escaped *all* boolean as lower case strings, including the one in the body. This commit fixes this and adds proper regression tests.
See https://twitter.com/aeris22/status/753989860000669696 for original discussion.

fix: (regression) body boolean must be sent as boolean

---

CHANGELOG.md
ovh/client.py
tests/test_consumer_key.py

SSL warnings are noisy, especially in CLI environments (poke @ncrocfer) and not actually relevant for python-ovh as we know the API has a dedicated IP per cert by design. We also have a vendored request lib so that this setting should not affect the end user.

Mute SNI warnings and upgrade requests

---

ovh/exceptions.py
tests/test_client.py

When it comes to API Exceptions, customers should be able to provide debugging informations in order to be able to track what's wrong on the other side of the API.
X-OVH-QUERYID is here for that. I think we should display that property in APIError class

feat(query-id): add query_id property to exceptions

---

debian/control

The package python3-setuptool is missing to build the package on a Debian stable (jessie).

Add build dependency on python3-setuptool in debian packaging.

---

README.rst
docs/index.rst
ovh/client.py
tests/fixtures/pwd_ovh.conf
tests/test_client.py
tests/test_config.py

Before releasing version 0.5.0 for @ncrocfer, I advise to remove mentions of runabove API. This API is no longer in use and no longer exposes any services. All customers using it have now migrated to OVH APIs (or there application stopped working long ago anyway)

Remove deprecated runabove API endpoint

---

ovh/client.py
tests/test_client.py

Signed-off-by: Geoffrey Bauduin <geoffrey.bauduin@corp.ovh.com>
The main idea here is to allow the caller to skip all the processing made on the requests response, hence allowing him to process himself the json as he wants to (that's just an example of usage, there are plenty others).

Adding raw_call method to retrieve directly the vendored requests.Response object

---

ovh/client.py
ovh/exceptions.py
tests/test_client.py

Signed-off-by: Alexandre Chaussier <alexandre.chaussier@temelio.com>
Hello,
I begin to wrote some scripts to work with your API and I've had error last days about an expired service.
To catch properly this case, I think a dedicated error can be useful.
Today, this service is not returned by the API so I don't have the return code, but I've found the toorop/ovh-cli/issues/1 issue and they catch the 460 code. I hope this have not changed.

Add ResourceExpiredError exception

---

.travis.yml

PyPi deployment procedure should be automatically trigerred by travis when commit on master is tagged with a tag.
**This requires to modify PyPi environment variable for the project to add ovh PyPi credentials for auto-deploy**

misc(travis): auto-deploy procedure to release on PyPi from travis

---

README.rst
ovh/client.py

Add US endpoint

---

README.rst
ovh/client.py

Hi please consider and merge this PR

Fix endpoint url in documentation and in client.py

---

ovh/client.py

Following #99 and #101, I change the behaviour when `None` is sent as a query parameter.
Also, do not send an empty query string `?` when no kwargs are provided.

fix: query parameters None should be JSON encoded and empty query params should not be sent

---

ovh/client.py
tests/test_client.py

Allows to specify parameters for *DELETE* requests as method parameters instead requiring to put them in url.
Examples on [api.ovh.com](https://api.ovh.com) are broken, because method `client.delete` doesn't support parameters.
Example of broken API: `/cloud/project/{projectId}/storage/{bucketId}`
Integrates #107

Update DELETE method to support params

---

ovh/client.py
tests/test_client.py

This feature aims at making available the use of headers while calling the OVH API.
The original behavior is preserved, as the signature changes with the introduction
of a non-mandatory parameter "header", which is None by default.
Added a piece of documentation to warn the user about the possbility
to have some headers being rewritten by the Client engine.
Signed-off-by: Geoffrey Bauduin <geoffrey.bauduin@corp.ovh.com>

feat: added support for headers when calling ovh.Client.raw_call
